"""
Django settings for kosmos project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t!bhx5bpe_-n_l3x%$78*twb!@ac5y%f2ot8w$y&=easpxah+9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "122.160.186.200"]

FRONTEND_URL = "http://localhost:3000"
LOGIN_REDIRECT_URL = FRONTEND_URL
LOGOUT_REDIRECT_URL = FRONTEND_URL
OLLAMA_URL = os.environ.get("OLLAMA_URL", "http://localhost:11434/api/chat")
OLLAMA_DASHBOARD_MODEL = os.environ.get("OLLAMA_DASHBOARD_MODEL", "llama3.1")

# ---------------------------------------------------------------------------
# SAML — Service Provider (this app)
# ---------------------------------------------------------------------------
SAML_SP_ENTITY_ID = "http://localhost:8000/api/auth/saml/metadata/"
SAML_SP_ACS_URL   = "http://localhost:8000/api/auth/saml/acs/"

SAML_SP_SLO_URL   = "http://localhost:8000/api/auth/saml/logout/"

# ---------------------------------------------------------------------------
# SAML — Identity Provider (1Kosmos)
# Paste the values from your 1Kosmos SAML app metadata here.
# ---------------------------------------------------------------------------
SAML_IDP_ENTITY_ID = ""           # e.g. "https://your-tenant.1kosmos.net/..."
SAML_IDP_SSO_URL   = ""           # e.g. "https://your-tenant.1kosmos.net/sso/saml"
SAML_IDP_X509_CERT = ""           # paste the base64 cert string (no header/footer needed)
SAML_IDP_SLO_URL   = ""           # leave blank if not using single-logout

SAML_STRICT              = False
SAML_DEBUG               = True
SAML_EMAIL_ATTRIBUTE     = "email"
SAML_FIRST_NAME_ATTRIBUTE = "firstName"
SAML_LAST_NAME_ATTRIBUTE  = "lastName"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'kosmos_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'kosmos_app.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", "false").lower() == "true"
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://122.160.186.200:3000",
]

ROOT_URLCONF = 'kosmos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kosmos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'kosmos',
        'USER': 'postgres',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# GitHub workflow used by Profile > Settings.
# Application files are edited inside the 1Kosmos workspace, while the
# existing Git metadata lives one directory above it.
GIT_REPOSITORY_ROOT = BASE_DIR.parent.resolve()
GIT_DIRECTORY = (BASE_DIR.parents[1] / ".git").resolve()
GIT_TRACKED_PATHS = ("kosmos", "kosmos_frontend")
GIT_EXCLUDED_PATHS = (
    "**/__pycache__/**",
    "**/*.pyc",
    "**/*.log",
    "**/*.err.log",
    "kosmos/db.sqlite3",
    "kosmos/venv/**",
    "kosmos_frontend/node_modules/**",
    "kosmos_frontend/build/**",
)
GIT_REPOSITORY_URL = "https://github.com/prabhatkrr562-ctrl/1Kosmos.git"
GIT_REMOTE_NAME = "origin"
GIT_MAIN_BRANCH = "main"
GIT_BRANCH_PREFIX = "kosmos/frontend-"
GIT_STATUS_REFRESH_INTERVAL_MS = 1000
