# Generated by Django 6.0.6 on 2026-06-22 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kosmos_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ARDataImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_name", models.CharField(max_length=255)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("as_of_date", models.DateField(blank=True, null=True)),
                ("aging_count", models.PositiveIntegerField(default=0)),
                ("payment_count", models.PositiveIntegerField(default=0)),
                ("renewal_count", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["-imported_at"]},
        ),
        migrations.CreateModel(
            name="ARRenewalRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("end_user", models.CharField(blank=True, max_length=255)),
                ("renewal_status", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(blank=True, max_length=150)),
                ("amount", models.FloatField(default=0)),
                ("sales_rep", models.CharField(blank=True, max_length=150)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("remarks", models.TextField(blank=True)),
                ("data_import", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="renewal_records", to="kosmos_app.ardataimport")),
            ],
        ),
        migrations.CreateModel(
            name="ARAgingRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer", models.CharField(blank=True, max_length=255)),
                ("end_user", models.CharField(blank=True, max_length=255)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("sales_rep", models.CharField(blank=True, max_length=150)),
                ("document_type", models.CharField(blank=True, max_length=50)),
                ("document_date", models.DateField(blank=True, null=True)),
                ("document_number", models.CharField(blank=True, max_length=150)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("open_balance", models.FloatField(default=0)),
                ("data_import", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="aging_records", to="kosmos_app.ardataimport")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["data_import", "region"], name="kosmos_app__data_im_f11075_idx"),
                    models.Index(fields=["data_import", "end_user"], name="kosmos_app__data_im_ac6d60_idx"),
                ]
            },
        ),
        migrations.CreateModel(
            name="ARPaymentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("invoice_number", models.CharField(blank=True, max_length=150)),
                ("customer", models.CharField(blank=True, max_length=255)),
                ("end_user", models.CharField(blank=True, max_length=255)),
                ("sales_rep", models.CharField(blank=True, max_length=150)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("payment_type", models.CharField(blank=True, max_length=50)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("amount", models.FloatField(default=0)),
                ("data_import", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_records", to="kosmos_app.ardataimport")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["data_import", "invoice_number"], name="kosmos_app__data_im_ae1c1f_idx"),
                    models.Index(fields=["data_import", "region"], name="kosmos_app__data_im_72f63d_idx"),
                ]
            },
        ),
    ]
