# Generated by Django 6.0.6 on 2026-06-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosmos_app', '0005_bookingrecord_attributes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pipelinerecord',
            new_name='kosmos_app__data_im_4478db_idx',
            old_name='kosmos_app__data_im_pip_week_idx',
        ),
        migrations.RenameIndex(
            model_name='pipelinerecord',
            new_name='kosmos_app__data_im_62316a_idx',
            old_name='kosmos_app__data_im_pip_stg_idx',
        ),
        migrations.RenameIndex(
            model_name='pipelinerecord',
            new_name='kosmos_app__data_im_a2485c_idx',
            old_name='kosmos_app__data_im_pip_own_idx',
        ),
        migrations.RemoveField(
            model_name='arpaymentrecord',
            name='source_of_payment',
        ),
        migrations.AddField(
            model_name='aragingrecord',
            name='attribute1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aragingrecord',
            name='attribute10',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aragingrecord',
            name='attribute2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aragingrecord',
            name='attribute3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aragingrecord',
            name='attribute4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aragingrecord',
            name='attribute5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aragingrecord',
            name='attribute6',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aragingrecord',
            name='attribute7',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aragingrecord',
            name='attribute8',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aragingrecord',
            name='attribute9',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aragingrecord',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aragingrecord',
            name='created_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='aragingrecord',
            name='last_update_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='aragingrecord',
            name='last_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ardataimport',
            name='attribute1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ardataimport',
            name='attribute2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ardataimport',
            name='attribute3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ardataimport',
            name='attribute4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ardataimport',
            name='attribute5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ardataimport',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ardataimport',
            name='created_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ardataimport',
            name='last_update_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ardataimport',
            name='last_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arpaymentrecord',
            name='attribute1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arpaymentrecord',
            name='attribute10',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arpaymentrecord',
            name='attribute2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arpaymentrecord',
            name='attribute3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arpaymentrecord',
            name='attribute4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arpaymentrecord',
            name='attribute5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arpaymentrecord',
            name='attribute6',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arpaymentrecord',
            name='attribute7',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arpaymentrecord',
            name='attribute8',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arpaymentrecord',
            name='attribute9',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arpaymentrecord',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arpaymentrecord',
            name='created_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='arpaymentrecord',
            name='last_update_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='arpaymentrecord',
            name='last_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrenewalrecord',
            name='attribute1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arrenewalrecord',
            name='attribute10',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arrenewalrecord',
            name='attribute2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arrenewalrecord',
            name='attribute3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arrenewalrecord',
            name='attribute4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arrenewalrecord',
            name='attribute5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arrenewalrecord',
            name='attribute6',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arrenewalrecord',
            name='attribute7',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arrenewalrecord',
            name='attribute8',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arrenewalrecord',
            name='attribute9',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arrenewalrecord',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrenewalrecord',
            name='created_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='arrenewalrecord',
            name='last_update_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='arrenewalrecord',
            name='last_update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
