# Generated by Django 6.0.6 on 2026-07-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kosmos_app', '0009_accessroleassignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accessroleassignment',
            new_name='kosmos_app__user_id_c75533_idx',
            old_name='kosmos_app_user_id_18b3ee_idx',
        ),
        migrations.RenameIndex(
            model_name='accessroleassignment',
            new_name='kosmos_app__role_7451de_idx',
            old_name='kosmos_app_role_66c93b_idx',
        ),
    ]
