# Generated by Django 6.0.6 on 2026-07-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosmos_app', '0010_rename_kosmos_app_user_id_18b3ee_idx_kosmos_app__user_id_c75533_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessroleassignment',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
