# Generated by Django 6.0.6 on 2026-07-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kosmos_app', '0012_accessauditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accessauditlog',
            new_name='kosmos_app__user_id_bb182e_idx',
            old_name='kosmos_app_user_id_9cb7cc_idx',
        ),
        migrations.RenameIndex(
            model_name='accessauditlog',
            new_name='kosmos_app__action_f70201_idx',
            old_name='kosmos_app_action_8a0f89_idx',
        ),
        migrations.RenameIndex(
            model_name='accessauditlog',
            new_name='kosmos_app__role_71a90a_idx',
            old_name='kosmos_app_role_b63072_idx',
        ),
    ]
