# Generated by Django 6.0.6 on 2026-07-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kosmos_app', '0017_accessuserprofile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accessuserprofile',
            new_name='kosmos_app__start_d_4fb941_idx',
            old_name='kosmos_app_start_d_8a0fb5_idx',
        ),
    ]
